package engines

import (
	"custom_erp/db"
	"database/sql"
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// The blanket per-field length cap applied when a field has no explicit
// max_length configured (every field today) is the "platform.field_max_length"
// setting - generous enough not to reject any real business data (the largest
// existing free-text fields in this codebase, e.g. audit log details or
// error stack traces, are logged separately, not stored via this generic
// doc-field path), tight enough to catch a genuinely oversized value.
// Stage 30.7 moved it from a constant to that setting (default still 10000);
// ValidateDocument reads it per call, see the length check below.

type FieldMeta struct {
	ID           string `json:"id"`
	DocTypeName  string `json:"doctype_name"`
	Fieldname    string `json:"fieldname"`
	Label        string `json:"label"`
	Fieldtype    string `json:"fieldtype"`
	Mandatory    bool   `json:"mandatory"`
	Options      string `json:"options"`
	DisplayOrder int    `json:"display_order"`
	// MaxLength (24.31) is nullable - nil means "no explicit per-field
	// limit configured," in which case ValidateDocument still applies
	// defaultFieldMaxLength as a blanket safety net. Set this to tighten
	// (or, up to the blanket cap, loosen) a specific field's own limit.
	MaxLength *int `json:"max_length,omitempty"`
	// AutoGenerated (Stage 30.6) marks a field the server fills in itself on
	// create - today, the document-number fields listed in
	// engines/document_numbering.go. It is derived, not stored: computing it
	// here means the generic record form renders those fields read-only from
	// the same registry that actually assigns them, instead of a hand-kept
	// copy of the list in JavaScript that would drift the first time a
	// doctype is added.
	AutoGenerated bool `json:"auto_generated,omitempty"`
	// Mirrored (Stage 30.5.6) marks a field that duplicates another field on
	// the same doctype and is filled from it server-side
	// (engines/document_mirror_fields.go) - PurchaseOrder.vendor_id against
	// .vendor. Derived the same way AutoGenerated is, and for the same
	// reason: the generic form drops the duplicate box instead of asking a
	// user to type the same value twice into two identically-named fields.
	Mirrored bool `json:"mirrored,omitempty"`
}

// GetDocTypeMeta retrieves the fields definition metadata for a doctype
func GetDocTypeMeta(tenantID string, doctype string) ([]FieldMeta, error) {
	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return nil, err
	}

	rows, err := db.DB.Query(fmt.Sprintf(`
		SELECT id, doctype_name, fieldname, label, fieldtype, mandatory, COALESCE(options, ''), display_order, max_length
		FROM %s.doctype_fields
		WHERE doctype_name = $1
		ORDER BY display_order ASC`, schema), doctype)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	autoNumbered := autoNumberedFields(doctype)
	mirrored := mirroredFieldNames(doctype)

	var fields []FieldMeta
	for rows.Next() {
		var f FieldMeta
		err := rows.Scan(&f.ID, &f.DocTypeName, &f.Fieldname, &f.Label, &f.Fieldtype, &f.Mandatory, &f.Options, &f.DisplayOrder, &f.MaxLength)
		if err != nil {
			return nil, err
		}
		f.AutoGenerated = autoNumbered[f.Fieldname]
		f.Mirrored = mirrored[f.Fieldname]
		fields = append(fields, f)
	}
	return fields, nil
}

// validFieldTypes is every fieldtype this codebase's own generic
// doc-validation switch (ValidateDocument, below) and frontend renderer
// actually understand - the exact set every doctype_fields migration in
// this repo already uses (grepped db/*.sql). SaveFieldDefinition's own
// caller (public/app.js's DocType Builder "Add Field" prompt) only ever
// suggests these six but is a free-text prompt with no client-side
// enforcement, so nothing before this stopped a typo (or "Currency"/
// "Attachment", types this codebase has no rendering/validation for at
// all) from being saved and then silently never format-checked.
// JSONTable/JSONMap (Stage 30.5.3) are the two structured types. They are
// stored exactly as the plain Data fields they replaced - a serialised JSON
// string in a text column - so every existing consumer reads what it always
// read; what they add is a column spec the generic form can render a line
// editor from, and the format check below, which these fields previously had
// none of at all.
var validFieldTypes = map[string]bool{
	"Data": true, "Number": true, "Date": true, "Select": true, "Link": true, "Check": true,
	"JSONTable": true, "JSONMap": true,
}

// jsonTableColumn is one column of a JSONTable field's spec, parsed from
// doctype_fields.options. Shared with the frontend, which renders the same
// spec as an add-line editor.
type jsonTableColumn struct {
	Key      string `json:"key"`
	Label    string `json:"label"`
	Type     string `json:"type"`
	Link     string `json:"link"`
	Required bool   `json:"required"`
}

// validateJSONTableValue checks that a JSONTable field holds a JSON array of
// objects and that every column its spec marks required is present and
// non-empty on every row.
//
// It deliberately does NOT verify link targets exist. A BOM's components list
// can be long, and one existence query per cell per save would turn a single
// document write into dozens of round trips; the line editor picks links from
// a live typeahead, and the engines that consume these lists already fail
// loudly on an unknown SKU. Shape is what was missing, and shape is what this
// checks - before 30.5.3 these were plain Data fields with no check at all,
// so `{"sku"` saved fine and blew up later inside the MRP explosion.
func validateJSONTableValue(f FieldMeta, valStr string) error {
	var rows []map[string]interface{}
	if err := json.Unmarshal([]byte(valStr), &rows); err != nil {
		return &ValidationError{Code: "GLOBAL-0002", SubFor: f.Label, Message: fmt.Sprintf("Field %q must be a JSON array of line items", f.Label)}
	}
	if f.Options == "" {
		return nil
	}
	var cols []jsonTableColumn
	if err := json.Unmarshal([]byte(f.Options), &cols); err != nil {
		// A malformed spec is a configuration bug, not a user error. Accepting
		// the value is the right failure direction: refusing every save on a
		// doctype whose metadata is mistyped would lock the tenant out of it.
		return nil
	}
	for i, row := range rows {
		for _, c := range cols {
			if !c.Required {
				continue
			}
			v, ok := row[c.Key]
			if !ok || v == nil || strings.TrimSpace(fmt.Sprintf("%v", v)) == "" {
				return &ValidationError{
					Code:    "GLOBAL-0001",
					SubFor:  f.Label,
					Message: fmt.Sprintf("Field %q line %d is missing %q", f.Label, i+1, c.Label),
				}
			}
		}
	}
	return nil
}

// SaveFieldDefinition adds or updates a field definition in a doctype metadata
func SaveFieldDefinition(tenantID string, doctype string, f FieldMeta) error {
	if !validFieldTypes[f.Fieldtype] {
		// META-0197 (Stage 25.5): "Unsupported field type."
		return &ValidationError{Code: "META-0197", Message: fmt.Sprintf("fieldtype %q is not supported", f.Fieldtype)}
	}

	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return err
	}

	// META-0201 (Stage 25.5): "Custom field name collision." The DocType
	// Builder frontend only ever offers "Add Field" (create), never "Edit
	// Field" - so from its own intended usage, re-submitting an existing
	// fieldname is always an unintended collision, not a deliberate edit.
	// Without this check the ON CONFLICT upsert below silently overwrites
	// whatever field (including a system field like "status") already used
	// that name.
	var existingID string
	err = db.DB.QueryRow(fmt.Sprintf(
		`SELECT id FROM %s.doctype_fields WHERE doctype_name = $1 AND fieldname = $2`, schema),
		doctype, f.Fieldname).Scan(&existingID)
	if err == nil {
		return &ValidationError{Code: "META-0201", Message: fmt.Sprintf("field %q already exists on %s", f.Fieldname, doctype)}
	}

	query := fmt.Sprintf(`
		INSERT INTO %s.doctype_fields (doctype_name, fieldname, label, fieldtype, mandatory, options, display_order, max_length)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
		ON CONFLICT (doctype_name, fieldname) DO UPDATE SET
			label = EXCLUDED.label,
			fieldtype = EXCLUDED.fieldtype,
			mandatory = EXCLUDED.mandatory,
			options = EXCLUDED.options,
			display_order = EXCLUDED.display_order,
			max_length = EXCLUDED.max_length`, schema)

	var opts interface{}
	if f.Options != "" {
		opts = f.Options
	} else {
		opts = nil
	}

	_, err = db.DB.Exec(query, doctype, f.Fieldname, f.Label, f.Fieldtype, f.Mandatory, opts, f.DisplayOrder, f.MaxLength)
	return err
}

// UpdateFieldDefinition edits an existing field definition in place, addressed
// by its row id rather than its fieldname - which is what lets the fieldname
// itself be corrected, the thing SaveFieldDefinition deliberately cannot do.
//
// SaveFieldDefinition is create-only on purpose (META-0201: a re-submitted
// fieldname there is always an accidental collision, never an intended edit),
// so before this there was no way at all to fix a typo'd label, a wrong
// fieldtype or a bad display order except delete-and-recreate - which throws
// away the field's stored data on every existing document. This is the missing
// half of that pair, and keeps the same two guards:
//
//   - META-0197 - the fieldtype must be one this engine actually renders.
//   - META-0201 - renaming onto a fieldname another row already owns is still
//     a collision. Excluding this row's own id is what makes "save without
//     changing the name" work rather than reporting a collision with itself.
//
// Renaming a fieldname does NOT rewrite the key inside existing documents'
// `data` blobs. That is deliberate and matches how the rest of this engine
// treats metadata: the JSONB payload is the record, the field list is a view
// over it, and a rename means the old key stops being displayed rather than
// being destroyed. Renaming back restores it. The UI warns before renaming.
func UpdateFieldDefinition(tenantID string, doctype string, fieldID string, f FieldMeta) error {
	if !validFieldTypes[f.Fieldtype] {
		return &ValidationError{Code: "META-0197", Message: fmt.Sprintf("fieldtype %q is not supported", f.Fieldtype)}
	}

	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return err
	}

	var clashID string
	err = db.DB.QueryRow(fmt.Sprintf(
		`SELECT id FROM %s.doctype_fields WHERE doctype_name = $1 AND fieldname = $2 AND id != $3`, schema),
		doctype, f.Fieldname, fieldID).Scan(&clashID)
	if err == nil {
		return &ValidationError{Code: "META-0201", Message: fmt.Sprintf("field %q already exists on %s", f.Fieldname, doctype)}
	} else if err != sql.ErrNoRows {
		return err
	}

	var opts interface{}
	if f.Options != "" {
		opts = f.Options
	}

	res, err := db.DB.Exec(fmt.Sprintf(`
		UPDATE %s.doctype_fields
		SET fieldname = $1, label = $2, fieldtype = $3, mandatory = $4, options = $5, display_order = $6, max_length = $7
		WHERE doctype_name = $8 AND id = $9`, schema),
		f.Fieldname, f.Label, f.Fieldtype, f.Mandatory, opts, f.DisplayOrder, f.MaxLength, doctype, fieldID)
	if err != nil {
		return err
	}
	// A zero-row UPDATE means the id doesn't belong to this doctype (a stale
	// screen, or a hand-crafted request). Reported rather than silently
	// succeeding, so the UI doesn't show "saved" over a no-op.
	if n, err := res.RowsAffected(); err == nil && n == 0 {
		return &ValidationError{Code: "META-0197", Message: fmt.Sprintf("no field %s exists on %s", fieldID, doctype)}
	}
	return nil
}

// DeleteFieldDefinition removes a field definition from metadata
func DeleteFieldDefinition(tenantID string, doctype string, fieldID string) error {
	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return err
	}
	_, err = db.DB.Exec(fmt.Sprintf("DELETE FROM %s.doctype_fields WHERE doctype_name = $1 AND id = $2", schema), doctype, fieldID)
	return err
}

// GetDocTypes returns all registered doctypes
func GetDocTypes(tenantID string) ([]map[string]interface{}, error) {
	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return nil, err
	}

	// setup_advanced (Stage 30.5.4) drives which side of the Setup menu's
	// "Advanced" divider a doctype lands on. COALESCE'd rather than assumed
	// present so this keeps working against a schema the migration has not
	// reached yet - everything simply reads as everyday, which is the safe
	// direction (an extra entry, never a hidden one).
	rows, err := db.DB.Query(fmt.Sprintf(
		"SELECT name, module, COALESCE(document_type, 'Master'), COALESCE(setup_advanced, FALSE) FROM %s.doctype_meta ORDER BY name", schema))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var list []map[string]interface{}
	for rows.Next() {
		var name, module, docType string
		var setupAdvanced bool
		if err := rows.Scan(&name, &module, &docType, &setupAdvanced); err != nil {
			return nil, err
		}
		list = append(list, map[string]interface{}{
			"name":           name,
			"module":         module,
			"document_type":  docType,
			"setup_advanced": setupAdvanced,
		})
	}
	return list, nil
}

// SaveDocType registers a new doctype definition in doctype_meta
func SaveDocType(tenantID string, name string, module string, docType string) error {
	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return err
	}

	query := fmt.Sprintf(`
		INSERT INTO %s.doctype_meta (name, module, document_type) 
		VALUES ($1, $2, $3) 
		ON CONFLICT (name) DO UPDATE SET 
			module = EXCLUDED.module, 
			document_type = EXCLUDED.document_type`, schema)
	_, err = db.DB.Exec(query, name, module, docType)
	return err
}

// ValidationError carries a precise error-catalog code (Stage 25, see
// internal/server/error_catalog_generated.go) alongside the same plain-text
// message ValidateDocument always returned - existing callers that only do
// err != nil / err.Error() (import.go, pim_bulk.go, engines_test.go) see no
// behavior change; handlers_core_doc_engine.go additionally type-asserts to
// attach the precise code+field instead of falling back to a generic one.
// Code is "" for the one internal-error path below with no catalog scenario
// (metadata lookup failure) - callers fall back to their own generic
// handling for that, same as before this type existed. The missing-doctype
// case (zero doctype_fields rows) got a real code, META-0196, in Stage 25.5.
type ValidationError struct {
	Code    string
	SubFor  string
	Message string
}

func (e *ValidationError) Error() string { return e.Message }

// ValidateDocument checks document properties against doctype_fields rules
func ValidateDocument(tenantID string, doctype string, docData map[string]interface{}) error {
	fields, err := GetDocTypeMeta(tenantID, doctype)
	if err != nil {
		return err
	}

	if len(fields) == 0 {
		// META-0196 (Stage 25.5): "DocType not registered" - a doctype with
		// zero doctype_fields rows (a typo'd doctype name from a client, or
		// a registered doctype_meta row with no matching fields ever
		// seeded) can't be validated or rendered as a real form.
		return &ValidationError{Code: "META-0196", Message: fmt.Sprintf("doctype %s metadata fields not found", doctype)}
	}

	// Stage 41: clean phone-shaped fields before anything else looks at
	// them, so the mandatory/length checks below - and everything downstream,
	// including what actually gets stored - see the canonical form rather than
	// whatever spacing and punctuation the channel/typist supplied. docData is
	// a map and therefore shared with the caller, which is what makes the
	// cleaned value reach the INSERT without a second wiring step.
	// Non-rejecting by design; see NormalizeDocumentPhones.
	fieldNames := make([]string, 0, len(fields))
	hasPhoneField := false
	for _, f := range fields {
		fieldNames = append(fieldNames, f.Fieldname)
		if IsPhoneField(f.Fieldname) {
			hasPhoneField = true
		}
	}
	if hasPhoneField {
		NormalizeDocumentPhones(tenantID, fieldNames, docData)
	}

	for _, f := range fields {
		val, exists := docData[f.Fieldname]
		valStr := ""
		if exists && val != nil {
			valStr = strings.TrimSpace(fmt.Sprintf("%v", val))
		}

		// 1. Mandatory check
		if f.Mandatory && valStr == "" {
			if f.Fieldname == "id" || f.Fieldname == "status" {
				// System fields are auto-generated or defaulted by the backend
			} else {
				return &ValidationError{Code: "GLOBAL-0001", SubFor: f.Label, Message: fmt.Sprintf("Field %q (%s) is required", f.Label, f.Fieldname)}
			}
		}

		// 1.5 Length check (24.31, loophole #12). f.MaxLength (per-field,
		// set via SaveFieldDefinition) tightens or loosens the blanket
		// platform.field_max_length safety net that applies to every field
		// today, since no field has one configured yet - the existing 2MB
		// whole-request-body cap (Stage 1.3) already bounds the extreme
		// case, this catches a single wildly-oversized field value inside
		// an otherwise-small request. No catalog code fits this scenario
		// (checked docs/specs/message_catalog.md), so this returns a
		// ValidationError with no Code - the shared handler call site
		// already falls back to a generic 422 with this message for
		// exactly that case, the same as any other uncataloged scenario.
		if valStr != "" {
			limit := GetSettingInt(tenantID, "platform.field_max_length")
			if f.MaxLength != nil && *f.MaxLength > 0 {
				limit = *f.MaxLength
			}
			if len(valStr) > limit {
				return &ValidationError{SubFor: f.Label, Message: fmt.Sprintf("Field %q (%s) exceeds the maximum allowed length of %d characters", f.Label, f.Fieldname, limit)}
			}
		}

		// 2. Type/Format check
		if valStr != "" {
			switch f.Fieldtype {
			case "Number":
				var num float64
				_, err := fmt.Sscanf(valStr, "%f", &num)
				if err != nil {
					return &ValidationError{Code: "GLOBAL-0002", SubFor: f.Label, Message: fmt.Sprintf("Field %q must be a valid number", f.Label)}
				}
			case "Select":
				if f.Options != "" {
					allowed := strings.Split(f.Options, ",")
					matched := false
					for _, o := range allowed {
						if strings.TrimSpace(o) == valStr {
							matched = true
							break
						}
					}
					if !matched {
						return &ValidationError{Code: "META-0199", Message: fmt.Sprintf("Field %q value %q is not in allowed list (%s)", f.Label, valStr, f.Options)}
					}
				}
			case "Link":
				if f.Options != "" { // options store target Doctype
					existsLink, err := verifyDocumentExists(tenantID, f.Options, valStr)
					if err != nil {
						return err
					}
					if !existsLink {
						return &ValidationError{Code: "META-0198", SubFor: f.Label, Message: fmt.Sprintf("Linked %s record with ID %q does not exist", f.Options, valStr)}
					}
				}
			case "JSONTable":
				if err := validateJSONTableValue(f, valStr); err != nil {
					return err
				}
			case "JSONMap":
				var obj map[string]interface{}
				if err := json.Unmarshal([]byte(valStr), &obj); err != nil {
					return &ValidationError{Code: "GLOBAL-0002", SubFor: f.Label, Message: fmt.Sprintf("Field %q must be a JSON object of key/value pairs", f.Label)}
				}
			}
		}
	}

	// Stage 40.2: format checks for the fields whose NAME says what kind of
	// value they hold - gstin, email, phone, pan, ifsc, pincode, url. Runs
	// last so a genuinely missing mandatory field still reports as missing
	// rather than as badly formatted, and after the phone normalisation above
	// so a number written "+91 (98765) 43210" is checked in its cleaned form.
	//
	// Never makes a field mandatory: an empty value passes every format.
	// See engines/field_formats.go for why this is keyed off the fieldname
	// rather than a new fieldtype.
	if err := ValidateDocumentFieldFormats(fields, docData); err != nil {
		return err
	}

	// Stage 36.1 / 37.1 foundations: domain rules for the new PIM group,
	// Currency and ExchangeRate masters. Keeping this at ValidateDocument's
	// shared exit means generic API saves and BulkImportCSV cannot disagree.
	if err := ValidateParityFoundationDocument(tenantID, doctype, docData); err != nil {
		return err
	}

	// Stage 37.1.2: stamp transaction currency, functional currency and the
	// base-currency amounts onto financial documents. Attached here, at the
	// shared exit, so a document saved through the generic API, a CSV import or
	// an engine cannot end up with a currency the others would disagree about.
	// A no-op for every doctype that is not currency-bearing, and a no-op for a
	// single-currency tenant beyond recording that the amount is already in its
	// own currency.
	if err := ApplyDocumentCurrency(tenantID, doctype, docData); err != nil {
		return err
	}

	return nil
}

func verifyDocumentExists(tenantID, doctype, id string) (bool, error) {
	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return false, err
	}
	var exists bool
	err = db.DB.QueryRow(fmt.Sprintf(`
		SELECT EXISTS(
			SELECT 1 FROM %s.documents 
			WHERE doctype = $1 AND id = $2 AND status != 'Cancelled'
		)`, schema), doctype, id).Scan(&exists)
	return exists, err
}

type IndustryProfile struct {
	IndustryCode     string            `json:"industry_code"`
	IndustryName     string            `json:"industry_name"`
	DocTypeOverrides []DocTypeOverride `json:"doctype_overrides"`
	Labels           map[string]string `json:"labels"`
}

type DocTypeOverride struct {
	Name         string      `json:"name"`
	Module       string      `json:"module"`
	DocumentType string      `json:"document_type"`
	NewLabel     string      `json:"new_label"`
	Fields       []FieldMeta `json:"fields"`
}

// SwitchIndustryProfile re-configures the dynamic doctypes, fields, and label translations based on an industry JSON configuration profile
func SwitchIndustryProfile(tenantID string, profilePath string) error {
	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return err
	}

	data, err := os.ReadFile(profilePath)
	if err != nil {
		return fmt.Errorf("failed to read profile path %s: %w", profilePath, err)
	}

	var prof IndustryProfile
	if err := json.Unmarshal(data, &prof); err != nil {
		return fmt.Errorf("failed to unmarshal profile JSON: %w", err)
	}

	tx, err := db.DB.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if err := db.SetSearchPath(tx, schema); err != nil {
		return err
	}

	// 1. Re-register doctypes and upsert field presets.
	// Deliberately does NOT delete existing fields first: industry profile JSON files are
	// partial overlays declaring the industry-specific additions/overrides for a doctype,
	// not its complete field list - none of the shipped profiles (jewelry/food_bev/auto/
	// clothing) redeclare base fields like "status". A prior delete-then-insert here silently
	// dropped any field a profile didn't mention on every single industry switch.
	for _, o := range prof.DocTypeOverrides {
		// Insert or update doctype meta
		metaQuery := fmt.Sprintf(`
			INSERT INTO doctype_meta (name, module, document_type)
			VALUES ($1, $2, $3)
			ON CONFLICT (name) DO UPDATE SET
				module = EXCLUDED.module,
				document_type = EXCLUDED.document_type`)
		_, err = tx.Exec(metaQuery, o.Name, o.Module, o.DocumentType)
		if err != nil {
			return fmt.Errorf("failed to register doctype %s: %w", o.Name, err)
		}

		// Upsert the profile's field presets - fields not mentioned by this profile are left untouched
		for _, f := range o.Fields {
			var opts interface{}
			if f.Options != "" {
				opts = f.Options
			}
			fieldQuery := fmt.Sprintf(`
				INSERT INTO doctype_fields (doctype_name, fieldname, label, fieldtype, mandatory, options, display_order)
				VALUES ($1, $2, $3, $4, $5, $6, $7)
				ON CONFLICT (doctype_name, fieldname) DO UPDATE SET
					label = EXCLUDED.label,
					fieldtype = EXCLUDED.fieldtype,
					mandatory = EXCLUDED.mandatory,
					options = EXCLUDED.options,
					display_order = EXCLUDED.display_order`)
			_, err = tx.Exec(fieldQuery, o.Name, f.Fieldname, f.Label, f.Fieldtype, f.Mandatory, opts, f.DisplayOrder)
			if err != nil {
				return fmt.Errorf("failed to save field %s for %s: %w", f.Fieldname, o.Name, err)
			}
		}
	}

	// 2. Clear old dynamic labels and insert custom translation maps
	_, _ = tx.Exec("DELETE FROM dynamic_labels")
	for orig, custom := range prof.Labels {
		labelQuery := fmt.Sprintf(`
			INSERT INTO dynamic_labels (original_text, custom_text) 
			VALUES ($1, $2)
			ON CONFLICT (original_text) DO UPDATE SET custom_text = EXCLUDED.custom_text`)
		_, err = tx.Exec(labelQuery, orig, custom)
		if err != nil {
			return fmt.Errorf("failed to save dynamic label %s: %w", orig, err)
		}
	}

	// 3. Log audit event
	auditQuery := fmt.Sprintf(`
		INSERT INTO audit_logs (user_id, action, status, details) 
		VALUES ($1, $2, $3, $4)`)
	auditDetails := fmt.Sprintf("Switched active industry profile to: %s (%s)", prof.IndustryName, prof.IndustryCode)
	_, err = tx.Exec(auditQuery, "admin", "SWITCH_INDUSTRY", "SUCCESS", auditDetails)
	if err != nil {
		return err
	}

	return tx.Commit()
}
