package engines

import (
	"custom_erp/db"
	"encoding/json"
	"fmt"
	"strings"
)

// HSN/SAC code catalogue (Stage 57.3).
//
// Item.hsn_code has always been free text, so the New Item form had nothing
// to pick from and no way to say "this HSN does not exist yet - create it".
// The user asked for exactly that: pick an HSN in New Item, or create the
// master on the spot.
//
// It is modelled on PurchaseRequisitionDescription rather than as a Link
// field, for two reasons:
//
//   - Item.hsn_code keeps storing the plain number ("6109"). The GST engine,
//     e-invoice and every report read that value as an HSN, so turning it
//     into a reference to some other identifier would break all of them.
//   - documents.id is unique across every doctype, so a record keyed on the
//     bare number could collide with any other master whose code is "6109".
//     The catalogue id is therefore "HSN-" + the number: deterministic, so a
//     second save of the same HSN converges on one record instead of
//     inventing a number series nobody asked for.
//
// The catalogue is a suggestion list, not a constraint. Saving an Item with
// an HSN that is not in it is still valid, and teaches it to the catalogue
// (EnsureHSNCode), the same way a new requirement wording is learned.

// serverDerivedFields are fields the server computes from the record's own
// values rather than from a numbering series - flagged AutoGenerated in the
// field metadata (GetDocTypeFields) so forms neither ask for them nor draw a
// sequence number for them. HSNCode.code is PrepareHSNCode's "HSN-" + number.
var serverDerivedFields = map[string]map[string]bool{
	"HSNCode": {"code": true},
}

// HSNCatalogID is the catalogue record id for one HSN/SAC number.
func HSNCatalogID(hsn string) string { return "HSN-" + hsn }

// NormalizeHSN strips the spaces and dots people type into HSN codes
// ("6109 10 00", "6109.10") so the same code is always stored one way.
func NormalizeHSN(raw string) string {
	return strings.NewReplacer(" ", "", ".", "", "\t", "").Replace(strings.TrimSpace(raw))
}

// validHSN accepts exactly what an Item accepts (MASTER-0043 in
// master_data_validation.go: 4, 6 or 8 digits; SAC service codes are 6), so
// every code in the catalogue can be used on an Item.
func validHSN(hsn string) bool {
	if len(hsn) != 4 && len(hsn) != 6 && len(hsn) != 8 {
		return false
	}
	for _, c := range hsn {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

// PrepareHSNCode normalizes and validates a catalogue record before metadata
// validation, and on create derives its code (and so, through the master
// id = code invariant, its id) from the number. Runs before ValidateDocument
// because code is mandatory and is supplied here, not by the user.
func PrepareHSNCode(isCreate bool, payload map[string]interface{}) error {
	raw, _ := payload["hsn"].(string)
	hsn := NormalizeHSN(raw)
	if hsn == "" {
		return fmt.Errorf("HSN/SAC code is required")
	}
	if !validHSN(hsn) {
		return fmt.Errorf("HSN/SAC code %q must be 4, 6 or 8 digits", raw)
	}
	payload["hsn"] = hsn
	if isCreate {
		payload["code"] = HSNCatalogID(hsn)
	}
	return nil
}

// EnsureHSNCode records an HSN seen on a saved Item, once. Silent for an
// empty or malformed value: the Item's own validation decides whether its
// HSN is acceptable, and the catalogue must never be the reason a save fails.
// An existing catalogue record is left untouched, so a rate an administrator
// set on it is never overwritten by whatever one Item happened to carry.
func EnsureHSNCode(tenantID, rawHSN string, gstRate float64) error {
	hsn := NormalizeHSN(rawHSN)
	if !validHSN(hsn) {
		return nil
	}
	schema, err := db.GetTenantSchema(tenantID)
	if err != nil {
		return err
	}
	data := map[string]interface{}{
		"code":        HSNCatalogID(hsn),
		"hsn":         hsn,
		"description": "",
		"status":      "Active",
	}
	if gstRate > 0 {
		data["gst_rate"] = gstRate
	}
	payload, err := json.Marshal(data)
	if err != nil {
		return err
	}
	_, err = db.DB.Exec(fmt.Sprintf(`
		INSERT INTO %s.documents (id, doctype, data, status, created_by)
		VALUES ($1, 'HSNCode', $2, 'Active', 'system')
		ON CONFLICT (id) DO NOTHING`, schema), HSNCatalogID(hsn), payload)
	return err
}
