-- Stage 30.5.4: mark the system-internal doctypes so the Setup menu can file
-- them behind an "Advanced" divider.
--
-- The Setup flyout is built at runtime from every Master doctype, which is
-- why it renders a flat alphabetical dump of 50+ technical names -
-- RoboticsIntegrationCredential and ChannelValidationRule interleaved with
-- Brand and Color. Grouping by `module` (already on every row) fixes most of
-- it, but a first-time user still should not meet channel field maps and
-- notification templates at the same level as Brand.
--
-- The flag lives on doctype_meta next to `module` and
-- `strict_status_transitions` rather than in a hardcoded list in app.js -
-- exactly the same reasoning as 30.6.4's FieldMeta.AutoGenerated: a doctype
-- list kept in JavaScript is a second source of truth that drifts the moment
-- anyone adds a doctype, and this one is admin-editable as a consequence.
--
-- Defaults FALSE, so a doctype added later is everyday-visible until someone
-- deliberately files it away. That is the safe direction to fail: an extra
-- entry in the main list is untidy, a hidden one is undiscoverable.

ALTER TABLE tenant_default.doctype_meta
  ADD COLUMN IF NOT EXISTS setup_advanced BOOLEAN NOT NULL DEFAULT FALSE;

-- The set is deliberately narrow: system plumbing that a business user
-- configures once (if ever), never business master data. Anything a shop
-- genuinely maintains - Brand, Color, Item, Vendor, Customer, Location,
-- Employee, Offer, ReasonCode, Printer, CartonType, TDSSection - stays in the
-- everyday list even where it is currently empty, because "empty" is a
-- 30.5.1 problem, not a reason to hide the way to fill it.
UPDATE tenant_default.doctype_meta
   SET setup_advanced = TRUE
 WHERE name IN (
   -- Integrations / channel plumbing
   'RoboticsIntegrationCredential',
   'ChannelCategoryMap',
   'ChannelFieldMap',
   'ChannelValidationRule',
   -- Engine rule tables driven by the OMS/WMS rather than a person
   'AllocationRule',
   'StatusTransitionRule',
   'BinReplenishmentRule',
   'CourierServiceArea',
   'NotificationChannelConfig',
   'NotificationTemplate',
   -- Operational records the system mints for itself
   'LPN',
   'StorageBillingRate',
   'PurchaseRequisitionDescription',
   -- Saved-view scaffolding for the report catalog
   'ReportColumnProfile',
   'ReportFilterPreset'
 );

-- Backfill every already-provisioned tenant schema. New tenants inherit the
-- column and the flags through ProvisionTenantSchema's clone of
-- tenant_default. Same loop shape as
-- migrations_stage29_8_status_transition_map.sql.
DO $$
DECLARE
  schema_rec RECORD;
BEGIN
  FOR schema_rec IN
    SELECT schema_name FROM information_schema.schemata
     WHERE schema_name LIKE 'tenant\_%' ESCAPE '\' AND schema_name <> 'tenant_default'
  LOOP
    IF to_regclass(format('%I.doctype_meta', schema_rec.schema_name)) IS NULL THEN
      CONTINUE;
    END IF;

    EXECUTE format('ALTER TABLE %I.doctype_meta ADD COLUMN IF NOT EXISTS setup_advanced BOOLEAN NOT NULL DEFAULT FALSE', schema_rec.schema_name);

    -- Copy tenant_default's decision rather than repeating the name list, so
    -- the two can never drift apart.
    EXECUTE format($f$
      UPDATE %I.doctype_meta m
         SET setup_advanced = d.setup_advanced
        FROM tenant_default.doctype_meta d
       WHERE d.name = m.name AND d.setup_advanced = TRUE
    $f$, schema_rec.schema_name);
  END LOOP;
END $$;
