-- Stage 29.8: per-doctype status-transition map.
--
-- Closes the half of ERP_LOOPHOLES_ANALYSIS.md's Medium #9 that was left open
-- as "[needs design decision]". The security-relevant half was already closed
-- (a bare doc write can't claim Approved/Rejected on an approval-gated
-- doctype, GLOBAL-0019 in handlers_core_doc_engine.go); what was missing was a
-- general valid-transition map for doctypes the approval engine does NOT own -
-- Masters' Active/Inactive, GRN/ProductionOrder/VendorInvoice's own richer
-- lifecycles. The user's decisions (2026-07-29):
--
--   * Enforcement: OPT-IN STRICT, per doctype. A transition with no rule is
--     allowed unless that doctype is explicitly flagged strict, so nothing
--     breaks on day one and tightening is per-doctype. (Not fail-closed
--     globally, which would have broken every engine-driven flow at once.)
--   * Scope of the first pass: transactional lifecycles AND masters.
--
-- This deliberately EXTENDS the existing StatusTransitionRule master (Stage
-- 26.12.9, engines/orders.go) rather than introducing a parallel mechanism -
-- it already has exactly the right shape (from_status/to_status/allowed/
-- requires_reason_code) and is already admin-editable through the generic
-- Master screen. Only two things were missing: it was limited to four OMS
-- entities, and nothing consulted it outside order cancellation.

-- 1. entity: was a Select limited to 'Order,OrderLine,FulfillmentOrder,
-- Shipment'. Widened to Data so any doctype name is accepted, validated in
-- code instead (engines/status_transition.go's validateStatusTransitionRule)
-- against the live doctype list plus those four legacy OMS entity names. Data
-- rather than a 50-value Select so a doctype added later needs no migration to
-- become governable.
UPDATE tenant_default.doctype_fields
   SET fieldtype = 'Data',
       options   = NULL,
       label     = 'Entity / Doctype'
 WHERE doctype_name = 'StatusTransitionRule' AND fieldname = 'entity';

-- 2. The per-doctype strict flag lives on doctype_meta, next to the rest of a
-- doctype's metadata, rather than in a new table - it is one boolean per
-- doctype and has exactly doctype_meta's lifetime. Defaults FALSE so every
-- doctype keeps today's fail-open behaviour until switched on.
ALTER TABLE tenant_default.doctype_meta
  ADD COLUMN IF NOT EXISTS strict_status_transitions BOOLEAN NOT NULL DEFAULT FALSE;

-- 3. Seed the matrices. Written as documents in the generic documents table
-- because that is what StatusTransitionRule already is - an ordinary Master,
-- editable from the existing UI, not a hardcoded table.
--
-- Master doctypes (Active/Inactive) are generated rather than listed, so every
-- current AND future Active/Inactive master is covered without anyone
-- maintaining a list by hand. Document ids are globally unique in this schema
-- (documents.id is the PK across all doctypes), hence the STR- prefix.
INSERT INTO tenant_default.documents (id, doctype, data, status, created_by)
SELECT
  'STR-' || f.doctype_name || '-' || t.from_status || '-' || t.to_status,
  'StatusTransitionRule',
  jsonb_build_object(
    'code',                 'STR-' || f.doctype_name || '-' || t.from_status || '-' || t.to_status,
    'entity',               f.doctype_name,
    'from_status',          t.from_status,
    'to_status',            t.to_status,
    'allowed',              'Yes',
    'requires_reason_code', 'No',
    'status',               'Active'
  ),
  'Active',
  'system'
FROM tenant_default.doctype_fields f
CROSS JOIN (VALUES ('Active', 'Inactive'), ('Inactive', 'Active')) AS t(from_status, to_status)
WHERE f.fieldname = 'status' AND f.options = 'Active,Inactive'
ON CONFLICT (id) DO NOTHING;

-- Transactional lifecycles, listed explicitly - these are the ones where an
-- illegal jump actually corrupts something (skipping a 3-way match, un-
-- cancelling a GRN whose stock already posted, re-capitalising a disposed
-- asset). Only legal edges are listed; strict mode denies everything else.
INSERT INTO tenant_default.documents (id, doctype, data, status, created_by)
SELECT
  'STR-' || v.entity || '-' || v.from_status || '-' || v.to_status,
  'StatusTransitionRule',
  jsonb_build_object(
    'code',                 'STR-' || v.entity || '-' || v.from_status || '-' || v.to_status,
    'entity',               v.entity,
    'from_status',          v.from_status,
    'to_status',            v.to_status,
    'allowed',              'Yes',
    'requires_reason_code', v.needs_reason,
    'status',               'Active'
  ),
  'Active',
  'system'
FROM (VALUES
  -- PurchaseOrder's live option set is Draft,Pending Approval,Approved,
  -- Rejected,Closed - the approval-engine states are generated by block 3b
  -- below, so only the domain edges are listed here.
  ('PurchaseOrder',   'Approved',        'Closed',          'No'),

  -- GRN: once Approved the stock has posted, so Approved is terminal apart
  -- from an explicit, reason-coded cancellation.
  ('GRN',             'Pending',         'Approved',        'No'),
  ('GRN',             'Pending',         'Cancelled',       'Yes'),
  ('GRN',             'Approved',        'Cancelled',       'Yes'),

  -- VendorInvoice: Draft -> Paid is exactly the jump that would skip the
  -- 3-way match, so it is simply absent.
  ('VendorInvoice',   'Draft',           'Matched',         'No'),
  ('VendorInvoice',   'Draft',           'MismatchHold',    'No'),
  ('VendorInvoice',   'Matched',         'Approved',        'No'),
  ('VendorInvoice',   'MismatchHold',    'Matched',         'No'),
  ('VendorInvoice',   'MismatchHold',    'Approved',        'Yes'),
  ('VendorInvoice',   'Approved',        'Paid',            'No'),

  ('SalesInvoice',    'Draft',           'Approved',        'No'),
  ('SalesInvoice',    'Approved',        'Paid',            'No'),
  ('SalesInvoice',    'Draft',           'Cancelled',       'Yes'),
  ('SalesInvoice',    'Approved',        'Cancelled',       'Yes'),

  ('ASN',             'Expected',        'Received',        'No'),
  ('ASN',             'Expected',        'Cancelled',       'Yes'),

  -- TransferOrder's live options include Packed between Approved and
  -- Dispatched (added after db/migration.sql's original three).
  ('TransferOrder',   'Draft',           'Approved',        'No'),
  ('TransferOrder',   'Approved',        'Packed',          'No'),
  ('TransferOrder',   'Packed',          'Dispatched',      'No'),
  ('TransferOrder',   'Approved',        'Dispatched',      'No'),
  ('TransferOrder',   'Dispatched',      'Received',        'No'),

  -- ProductionOrder's live options include In Process between Material
  -- Issued and Completed; both the staged and the direct path are legal
  -- (engines/manufacturing.go completes straight from Material Issued).
  ('ProductionOrder', 'Draft',           'Material Issued', 'No'),
  ('ProductionOrder', 'Material Issued', 'In Process',      'No'),
  ('ProductionOrder', 'In Process',      'Completed',       'No'),
  ('ProductionOrder', 'Material Issued', 'Completed',       'No'),

  -- Asset: Disposed is terminal - re-capitalising a disposed asset would
  -- silently resurrect depreciation on something that no longer exists.
  ('Asset',           'Draft',           'Capitalised',     'No'),
  ('Asset',           'Capitalised',     'Disposed',        'Yes'),

  -- Approval-engine edges for these three are generated by block 3b; only
  -- their post-approval domain steps are listed here.
  ('ExpenseClaim',    'Approved',        'Verified',        'No'),
  ('ExpenseClaim',    'Verified',        'Paid',            'No'),

  ('PurchaseRequisition', 'Approved',         'Converted',        'No'),

  -- CycleCountLine's live options include Recount Requested, which a
  -- reviewer can send a variance back to instead of approving it outright.
  ('CycleCountLine',  'Approved',         'Posted',           'No'),
  ('CycleCountLine',  'Pending Approval', 'Recount Requested', 'Yes'),
  ('CycleCountLine',  'Recount Requested', 'Draft',            'No'),
  ('CycleCountLine',  'Recount Requested', 'Pending Approval', 'No'),

  ('ReturnRequest',   'Requested',       'Approved',        'No'),
  ('ReturnRequest',   'Requested',       'Rejected',        'Yes'),
  ('ReturnRequest',   'Approved',        'Received',        'No'),
  ('ReturnRequest',   'Received',        'QC Complete',     'No'),
  ('ReturnRequest',   'QC Complete',     'Closed',          'No'),

  ('RefundRequest',   'Pending',         'Approved',        'No'),
  ('RefundRequest',   'Pending',         'Rejected',        'Yes'),
  ('RefundRequest',   'Approved',        'Processed',       'No'),

  ('RFQ',             'Draft',           'Sent',            'No'),
  ('RFQ',             'Sent',            'Closed',          'No'),

  ('VendorQuote',     'Submitted',       'Selected',        'No'),
  ('VendorQuote',     'Submitted',       'Rejected',        'Yes'),

  ('Leave',           'Applied',         'Approved',        'No'),
  ('Leave',           'Applied',         'Rejected',        'Yes'),

  ('POSSession',      'Open',            'Closed',          'No'),
  ('Manifest',        'Open',            'Handed Over',     'No'),
  ('DebitNote',       'Draft',           'Posted',          'No'),
  ('CreditNote',      'Draft',           'Posted',          'No'),
  ('PaymentProposal', 'Draft',           'Executed',        'No'),
  ('MarketplaceSettlement', 'Unreconciled', 'Reconciled',   'No'),
  ('ProductContent',  'Approved',        'Draft',           'No')
) AS v(entity, from_status, to_status, needs_reason)
ON CONFLICT (id) DO NOTHING;

-- 3b. Approval-engine edges, GENERATED from each doctype's own live status
-- options rather than hand-listed.
--
-- This block exists because hand-listing got it wrong: the explicit matrices
-- above were first written from db/migration.sql's original option strings,
-- but later migrations extended several doctypes (PurchaseOrder gained
-- 'Pending Approval'/'Rejected', ProductionOrder gained 'In Process',
-- TransferOrder gained 'Packed', CycleCountLine gained 'Recount Requested').
-- Testing on a clone of the dev database found a real PurchaseOrder sitting in
-- 'Pending Approval' that strict mode would have frozen permanently. Deriving
-- the approval states from the live options instead of a static list means a
-- doctype that gains them later is covered without anyone remembering to.
--
-- Draft->Approved is included because the approval engine can auto-approve
-- below-threshold documents; it stays independently guarded by GLOBAL-0019 for
-- approval-gated doctypes, which is a separate check from this map.
INSERT INTO tenant_default.documents (id, doctype, data, status, created_by)
SELECT
  'STR-' || f.doctype_name || '-' || e.from_status || '-' || e.to_status,
  'StatusTransitionRule',
  jsonb_build_object(
    'code',                 'STR-' || f.doctype_name || '-' || e.from_status || '-' || e.to_status,
    'entity',               f.doctype_name,
    'from_status',          e.from_status,
    'to_status',            e.to_status,
    'allowed',              'Yes',
    'requires_reason_code', e.needs_reason,
    'status',               'Active'
  ),
  'Active',
  'system'
FROM tenant_default.doctype_fields f
CROSS JOIN (VALUES
  ('Draft',            'Pending Approval', 'No'),
  ('Draft',            'Approved',         'No'),
  ('Pending Approval', 'Approved',         'No'),
  ('Pending Approval', 'Rejected',         'Yes'),
  ('Pending Approval', 'Draft',            'No'),
  -- Approved -> Pending Approval is what ResetToPendingOnEdit does when an
  -- already-approved document is edited; it must be legal or every re-approval
  -- would be blocked.
  ('Approved',         'Pending Approval', 'No'),
  ('Rejected',         'Draft',            'No'),
  ('Rejected',         'Pending Approval', 'No')
) AS e(from_status, to_status, needs_reason)
WHERE f.fieldname = 'status'
  AND f.options <> 'Active,Inactive'
  -- Restricted to doctypes block 3 already gave a matrix to: the strict flag
  -- isn't set until step 4 below, so "has a seeded rule" is the same
  -- condition, evaluated at a point where it already holds.
  AND EXISTS (
    SELECT 1 FROM tenant_default.documents r
     WHERE r.doctype = 'StatusTransitionRule' AND r.created_by = 'system'
       AND r.data->>'entity' = f.doctype_name
  )
  -- Only generate an edge when BOTH of its endpoints are real options for
  -- this doctype, so e.g. GRN (Pending/Approved/Cancelled) gets nothing here.
  AND (',' || f.options || ',') LIKE ('%,' || e.from_status || ',%')
  AND (',' || f.options || ',') LIKE ('%,' || e.to_status || ',%')
ON CONFLICT (id) DO NOTHING;

-- 4. Turn strict on for exactly the doctypes seeded above, and only those.
-- A doctype with a matrix but no strict flag would be nearly inert (fail-open
-- means a missing edge is still allowed), so seeding and flagging are one
-- step. Everything else in the system stays fail-open, unchanged.
--
-- Deliberately NOT flagged strict: worker-driven types (ImportJob,
-- ReportExportJob, POSOfflineQueueGap, POSOfflineSyncVariance) whose status is
-- written by background code rather than a person, and the four legacy OMS
-- entities (Order/OrderLine/FulfillmentOrder/Shipment), which are not doctypes
-- and keep their existing cancellation-matrix behaviour untouched.
UPDATE tenant_default.doctype_meta m
   SET strict_status_transitions = TRUE
 WHERE EXISTS (
   SELECT 1 FROM tenant_default.documents d
    WHERE d.doctype = 'StatusTransitionRule'
      AND d.deleted_at IS NULL
      AND d.data->>'entity' = m.name
 );

-- 5. Backfill every already-provisioned tenant schema. New tenants inherit all
-- of the above through ProvisionTenantSchema (doctype_meta/doctype_fields/
-- documents are all in its clone+seed lists). Same loop shape as
-- migrations_stage27_product_packaging.sql.
DO $$
DECLARE
  schema_rec RECORD;
BEGIN
  FOR schema_rec IN
    SELECT schema_name FROM information_schema.schemata
     WHERE schema_name LIKE 'tenant\_%' ESCAPE '\' AND schema_name <> 'tenant_default'
  LOOP
    IF to_regclass(format('%I.doctype_meta', schema_rec.schema_name)) IS NULL THEN
      CONTINUE;
    END IF;

    EXECUTE format('ALTER TABLE %I.doctype_meta ADD COLUMN IF NOT EXISTS strict_status_transitions BOOLEAN NOT NULL DEFAULT FALSE', schema_rec.schema_name);

    EXECUTE format($f$
      UPDATE %I.doctype_fields SET fieldtype = 'Data', options = NULL, label = 'Entity / Doctype'
       WHERE doctype_name = 'StatusTransitionRule' AND fieldname = 'entity'
    $f$, schema_rec.schema_name);

    -- Copy tenant_default's freshly-seeded rules across rather than repeating
    -- the VALUES list, so the two can never drift apart.
    EXECUTE format($f$
      INSERT INTO %I.documents (id, doctype, data, status, created_by)
      SELECT id, doctype, data, status, created_by
        FROM tenant_default.documents
       WHERE doctype = 'StatusTransitionRule' AND created_by = 'system'
      ON CONFLICT (id) DO NOTHING
    $f$, schema_rec.schema_name);

    EXECUTE format($f$
      UPDATE %I.doctype_meta m SET strict_status_transitions = TRUE
       WHERE EXISTS (
         SELECT 1 FROM %I.documents d
          WHERE d.doctype = 'StatusTransitionRule' AND d.deleted_at IS NULL
            AND d.data->>'entity' = m.name
       )
    $f$, schema_rec.schema_name, schema_rec.schema_name);
  END LOOP;
END $$;
