-- Stage 26.4.11 (PIM/PXM Sprint): product content assist.
--
-- Scope decision (user, 2026-08-06): LOCAL/OFFLINE ONLY. The generator composes
-- a draft from the product's own Item fields and resolved family attribute
-- values using deterministic templates (engines/pim_content_assist.go). No
-- model provider, no API key, no network call - so no PIM content, and in
-- particular no supplier-submitted text (26.4.10), leaves this server. That
-- answers go_live_decisions.md section 11's questions 1, 4 and 5 by
-- construction rather than by policy.
--
-- ContentAssistLog is the audit trail for question 3 ("tell AI-authored from
-- human-authored content after the fact"). It is a plain system-written log
-- doctype - the same "engine writes directly into documents, no bespoke table"
-- precedent StockLedgerEntry set and ReportRunLog (26.10.7) followed, chosen
-- again here specifically because a bespoke table would need an entry in
-- ProvisionTenantSchema's clone list, which is exactly what drifted and cost
-- every new tenant its GL/approvals/WMS tables until 26.11.2 caught it.
--
-- No role gets create/update/delete via the generic API: writeContentAssistLog
-- inserts directly, so read-only is the complete and correct permission set.
-- Rows are evidence of what was generated; letting anyone edit them through the
-- API would defeat the point of keeping them.
--
-- Question 2 (human-in-the-loop) needs no schema at all: the engine returns a
-- suggestion and never writes ProductContent, so an accepted draft is saved by
-- a person as an ordinary Draft and still passes the existing Stage 15.1/26.4.5
-- approval gate before it can publish.
INSERT INTO tenant_default.doctype_meta (name, module, document_type, module_key) VALUES
('ContentAssistLog', 'PIM', 'Transaction', 'pim')
ON CONFLICT (name) DO NOTHING;

INSERT INTO tenant_default.doctype_fields (doctype_name, fieldname, label, fieldtype, mandatory, options, display_order) VALUES
('ContentAssistLog', 'item_code', 'Item', 'Data', TRUE, NULL, 1),
('ContentAssistLog', 'language', 'Language', 'Data', TRUE, NULL, 2),
-- Names the generator, not a model: if a real model call ever replaces the
-- local templates, existing rows stay unambiguous about what produced them.
('ContentAssistLog', 'generator', 'Generated By', 'Data', TRUE, NULL, 3),
('ContentAssistLog', 'suggested_title', 'Suggested Title', 'Data', FALSE, NULL, 4),
('ContentAssistLog', 'suggested_short_desc', 'Suggested Short Description', 'Text', FALSE, NULL, 5),
('ContentAssistLog', 'suggested_long_desc', 'Suggested Long Description', 'Text', FALSE, NULL, 6),
('ContentAssistLog', 'suggested_seo_title', 'Suggested SEO Title', 'Data', FALSE, NULL, 7),
('ContentAssistLog', 'suggested_tags', 'Suggested Tags', 'Data', FALSE, NULL, 8),
-- Provenance: which item fields and attributes the draft was actually built
-- from, so a reviewer can judge what the text rests on.
('ContentAssistLog', 'source_fields', 'Source Fields', 'Text', FALSE, NULL, 9),
('ContentAssistLog', 'user_id', 'Generated For', 'Data', FALSE, NULL, 10)
ON CONFLICT (doctype_name, fieldname) DO NOTHING;

INSERT INTO tenant_default.role_permissions (role, doctype_name, allow_read, allow_create, allow_update, allow_delete) VALUES
('HR/Admin', 'ContentAssistLog', TRUE, FALSE, FALSE, FALSE)
ON CONFLICT (role, doctype_name) DO NOTHING;
