#!/usr/bin/env python3
"""Regenerates internal/server/error_catalog_generated.go from the ERP
Standard Message Control Matrix xlsx (Stage 23).

This is a dev-time code generator only - it is never imported or run by the
Go binary, so it does not add a runtime dependency. Run it whenever the
source xlsx changes:

    py scripts/gen_error_catalog.py <path-to-xlsx>

Requires openpyxl (pip install openpyxl); not vendored into go.mod/go.sum.
"""
import json
import re
import sys

try:
    import openpyxl
except ImportError:
    print("This script needs openpyxl: pip install openpyxl", file=sys.stderr)
    sys.exit(1)

DEFAULT_XLSX = r"C:\Users\ABCD\Downloads\MyBusiness\IT Solution\ERP\Doc\ERP_Standard_Message_Control_Matrix_Final.xlsx"
OUT_PATH = "internal/server/error_catalog_generated.go"


def go_str(value) -> str:
    """Quote a value as a Go double-quoted string literal. json.dumps uses the
    same backslash/quote/control-char escaping rules as Go string literals
    for plain-ASCII/Unicode text, so it's a safe, dependency-free encoder."""
    return json.dumps("" if value is None else str(value).strip())


def go_bool(value: str) -> str:
    return "true" if str(value).strip().lower() == "true" else "false"


def load_rows(xlsx_path):
    wb = openpyxl.load_workbook(xlsx_path, data_only=True)
    ws = wb["Final Matrix"]
    rows = list(ws.iter_rows(values_only=True))
    header = rows[0]
    col = {name: i for i, name in enumerate(header)}
    return col, rows[1:]


def main():
    xlsx_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_XLSX
    col, data = load_rows(xlsx_path)

    entries = []
    seen_codes = set()
    for r in data:
        code = str(r[col["Error Code"]]).strip()
        if not code or code == "None":
            continue
        if code in seen_codes:
            raise SystemExit(f"duplicate Error Code in source matrix: {code}")
        seen_codes.add(code)

        http_status = r[col["HTTP Status"]]
        try:
            http_status = int(http_status)
        except (TypeError, ValueError):
            http_status = 0

        log_required = str(r[col["Log Required?"]]).strip() != "No"
        audit_required = str(r[col["Audit Required?"]]).strip() == "Yes"
        retryable = str(r[col["Retryable?"]]).strip() == "Yes"
        blocking = str(r[col["Blocking?"]]).strip() == "Yes"

        entries.append({
            "code": code,
            "message_id": r[col["Message ID"]],
            "module": r[col["Module"]],
            "scenario": r[col["Scenario / Validation Trigger"]],
            "message_type": r[col["Message Type"]],
            "user_message": r[col["Standard User Message"]],
            "user_action": r[col["User Action / Resolution"]],
            "severity": r[col["Severity"]],
            "blocking": blocking,
            "display_style": r[col["Display Style"]],
            "http_status": http_status,
            "retryable": retryable,
            "log_required": log_required,
            "audit_required": audit_required,
            "priority": r[col["Priority"]],
            "requirement_level": r[col["Requirement Level"]],
        })

    entries.sort(key=lambda e: e["code"])

    lines = []
    lines.append("// Code generated by scripts/gen_error_catalog.py from")
    lines.append("// ERP_Standard_Message_Control_Matrix_Final.xlsx (Stage 23). DO NOT EDIT BY HAND.")
    lines.append("// Regenerate: py scripts/gen_error_catalog.py <path-to-xlsx>")
    lines.append("")
    lines.append("package server")
    lines.append("")
    lines.append("// CatalogEntry is one row of the standardized error/message matrix -")
    lines.append("// the single source of truth for what an API error response says, its")
    lines.append("// HTTP status, severity, and whether it must be logged/audited.")
    lines.append("type CatalogEntry struct {")
    lines.append("\tCode             string")
    lines.append("\tMessageID        string")
    lines.append("\tModule           string")
    lines.append("\tScenario         string")
    lines.append("\tMessageType      string")
    lines.append("\tUserMessage      string")
    lines.append("\tUserAction       string")
    lines.append("\tSeverity         string")
    lines.append("\tBlocking         bool")
    lines.append("\tDisplayStyle     string")
    lines.append("\tHTTPStatus       int")
    lines.append("\tRetryable        bool")
    lines.append("\tLogRequired      bool")
    lines.append("\tAuditRequired    bool")
    lines.append("\tPriority         string")
    lines.append("\tRequirementLevel string")
    lines.append("}")
    lines.append("")
    lines.append(f"// errorCatalog holds all {len(entries)} standardized message codes, keyed by")
    lines.append("// Error Code (e.g. \"GLOBAL-0001\", \"MASTER-0040\"). See docs/specs/message_catalog.md.")
    lines.append("var errorCatalog = map[string]CatalogEntry{")
    for e in entries:
        lines.append(f"\t{go_str(e['code'])}: {{")
        lines.append(f"\t\tCode:             {go_str(e['code'])},")
        lines.append(f"\t\tMessageID:        {go_str(e['message_id'])},")
        lines.append(f"\t\tModule:           {go_str(e['module'])},")
        lines.append(f"\t\tScenario:         {go_str(e['scenario'])},")
        lines.append(f"\t\tMessageType:      {go_str(e['message_type'])},")
        lines.append(f"\t\tUserMessage:      {go_str(e['user_message'])},")
        lines.append(f"\t\tUserAction:       {go_str(e['user_action'])},")
        lines.append(f"\t\tSeverity:         {go_str(e['severity'])},")
        lines.append(f"\t\tBlocking:         {'true' if e['blocking'] else 'false'},")
        lines.append(f"\t\tDisplayStyle:     {go_str(e['display_style'])},")
        lines.append(f"\t\tHTTPStatus:       {e['http_status']},")
        lines.append(f"\t\tRetryable:        {'true' if e['retryable'] else 'false'},")
        lines.append(f"\t\tLogRequired:      {'true' if e['log_required'] else 'false'},")
        lines.append(f"\t\tAuditRequired:    {'true' if e['audit_required'] else 'false'},")
        lines.append(f"\t\tPriority:         {go_str(e['priority'])},")
        lines.append(f"\t\tRequirementLevel: {go_str(e['requirement_level'])},")
        lines.append("\t},")
    lines.append("}")
    lines.append("")

    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    print(f"Wrote {OUT_PATH}: {len(entries)} entries")


if __name__ == "__main__":
    main()
